import re
from collections import defaultdict

from app.schemas.ads_script import ParsedAd, ParsedKeyword, ParsedWorkbook

LOCATION_CODES: dict[str, int] = {
    "US": 2840,
    "UK": 2826,
    "CA": 2124,
    "AU": 2036,
    "DE": 2276,
    "FR": 2250,
}

PIN_POSITION_MAP: dict[int, str] = {
    1: "HEADLINE_1",
    2: "HEADLINE_2",
    3: "HEADLINE_3",
}

BIDDING_STRATEGY_MAP: dict[str, str] = {
    "manual_cpc": "MANUAL_CPC",
    "maximize_clicks": "MAXIMIZE_CLICKS",
    "maximize_conversions": "MAXIMIZE_CONVERSIONS",
    "target_cpa": "TARGET_CPA",
    "target_roas": "TARGET_ROAS",
}


def generate_script(data: ParsedWorkbook) -> str:
    lines: list[str] = []
    campaign = data.campaign

    _write_header(lines, campaign.name)
    lines.append("function main() {")
    _write_duplicate_check(lines, campaign.name)
    _write_campaign_creation(lines, campaign)
    _write_ad_groups(lines, data)
    _write_negative_keywords(lines, data)
    _write_location_targeting(lines, data)
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def _write_header(lines: list[str], campaign_name: str) -> None:
    lines.append("// Google Ads Script")
    lines.append(f"// Campaign: {_escape_js(campaign_name)}")
    lines.append("// Generated by CampaignLauncher")
    lines.append("//")
    lines.append("// Instructions:")
    lines.append("// 1. In Google Ads, go to Tools > Bulk Actions > Scripts")
    lines.append("// 2. Click the + button to create a new script")
    lines.append("// 3. Paste this entire script into the editor")
    lines.append("// 4. Click Authorize and grant permissions")
    lines.append("// 5. Click Preview to test without making changes")
    lines.append("// 6. Click Run to create the campaign")
    lines.append("")


def _write_duplicate_check(lines: list[str], campaign_name: str) -> None:
    safe_name = _escape_js(campaign_name)
    lines.append(f'  var existingCampaigns = AdsApp.campaigns().withCondition("Name = \'{safe_name}\'").get();')
    lines.append("  if (existingCampaigns.hasNext()) {")
    lines.append(f'    Logger.log("Campaign \'{safe_name}\' already exists. Aborting to prevent duplicates.");')
    lines.append("    return;")
    lines.append("  }")
    lines.append("")


def _write_campaign_creation(lines: list[str], campaign) -> None:
    name = _escape_js(campaign.name)
    budget = campaign.daily_budget
    strategy = _format_bidding_strategy(campaign.bidding_strategy)

    lines.append(f'  var campaignBuilder = AdsApp.newCampaignBuilder()')
    lines.append(f'    .withName("{name}")')
    lines.append(f"    .withBudget({budget})")
    lines.append(f'    .withBiddingStrategy("{strategy}")')
    lines.append(f'    .withStatus("PAUSED");')
    lines.append("")
    lines.append("  var campaignOperation = campaignBuilder.build();")
    lines.append("  var campaign = campaignOperation.getResult();")
    lines.append(f'  Logger.log("Created campaign: {name}");')
    lines.append("")


def _write_ad_groups(lines: list[str], data: ParsedWorkbook) -> None:
    # Group keywords and ads by ad group name
    kw_by_group: dict[str, list[ParsedKeyword]] = defaultdict(list)
    for kw in data.keywords:
        kw_by_group[kw.ad_group].append(kw)

    ads_by_group: dict[str, list[ParsedAd]] = defaultdict(list)
    for ad in data.ads:
        ads_by_group[ad.ad_group].append(ad)

    all_groups = sorted(set(list(kw_by_group.keys()) + list(ads_by_group.keys())))

    for i, group_name in enumerate(all_groups):
        var_name = _safe_var_name(group_name, i)
        safe_name = _escape_js(group_name)
        bid_value = data.campaign.bid_value or 1.0

        lines.append(f"  // Ad Group: {safe_name}")
        lines.append(f"  var {var_name} = campaign.newAdGroupBuilder()")
        lines.append(f'    .withName("{safe_name}")')
        lines.append(f"    .withCpc({bid_value})")
        lines.append(f'    .withStatus("ENABLED")')
        lines.append(f"    .build()")
        lines.append(f"    .getResult();")
        lines.append("")

        # Keywords
        for kw in kw_by_group.get(group_name, []):
            formatted = _format_keyword(kw.text, kw.match_type)
            bid_str = ""
            if kw.bid is not None:
                bid_str = f".withCpc({kw.bid})"
            lines.append(f"  {var_name}.newKeywordBuilder()")
            lines.append(f'    .withText("{formatted}")')
            if bid_str:
                lines.append(f"    {bid_str}")
            lines.append(f"    .build();")

        if kw_by_group.get(group_name):
            lines.append("")

        # Ads (RSAs)
        for ad in ads_by_group.get(group_name, []):
            _write_rsa(lines, var_name, ad)


def _write_rsa(lines: list[str], ag_var: str, ad: ParsedAd) -> None:
    final_url = _escape_js(ad.final_url)
    lines.append(f"  var adBuilder = {ag_var}.newAd().responsiveSearchAdBuilder()")
    lines.append(f'    .withFinalUrl("{final_url}")')

    # Headlines
    for h in ad.headlines:
        text = _escape_js(h.text)
        if h.pin_position and h.pin_position in PIN_POSITION_MAP:
            pin = PIN_POSITION_MAP[h.pin_position]
            lines.append(f'    .addHeadline("{text}", "{pin}")')
        else:
            lines.append(f'    .addHeadline("{text}")')

    # Descriptions
    for d in ad.descriptions:
        text = _escape_js(d.text)
        lines.append(f'    .addDescription("{text}")')

    # Paths
    if ad.path1:
        lines.append(f'    .withPath1("{_escape_js(ad.path1)}")')
    if ad.path2:
        lines.append(f'    .withPath2("{_escape_js(ad.path2)}")')

    lines.append("    .build();")
    lines.append("")


def _write_negative_keywords(lines: list[str], data: ParsedWorkbook) -> None:
    negatives = data.campaign.negative_keywords
    if not negatives:
        return

    lines.append("  // Negative keywords")
    for neg in negatives:
        safe = _escape_js(neg.strip())
        lines.append(f'  campaign.createNegativeKeyword("{safe}");')
    lines.append("")


def _write_location_targeting(lines: list[str], data: ParsedWorkbook) -> None:
    location = data.campaign.location_targeting
    if not location:
        return

    lines.append("  // Location targeting")
    locations = [loc.strip() for loc in location.split(",") if loc.strip()]
    for loc in locations:
        code = LOCATION_CODES.get(loc.upper())
        if code:
            lines.append(f"  campaign.addLocation({code}); // {loc}")
        else:
            lines.append(f"  // Unknown location: {_escape_js(loc)} -- add manually in Google Ads")
    lines.append("")


def _safe_var_name(group_name: str, index: int) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9]", "", group_name)
    if not cleaned or not cleaned[0].isalpha():
        cleaned = "adGroup" + cleaned
    return f"{cleaned}_{index}"


def _escape_js(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("'", "\\'")


def _format_keyword(text: str, match_type: str) -> str:
    mt = match_type.lower()
    if mt == "exact":
        return f"[{text}]"
    if mt == "phrase":
        return f'\\"{text}\\"'
    # broad match: plain text
    return text


def _format_bidding_strategy(strategy: str) -> str:
    return BIDDING_STRATEGY_MAP.get(strategy, strategy.upper())
