"""initial schema

Revision ID: 41f5195956f4
Revises: 
Create Date: 2026-03-02 20:59:27.399416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41f5195956f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('landing_page_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'APPROVED', 'LAUNCHED', 'PAUSED', name='campaignstatus', native_enum=False), nullable=False),
    sa.Column('bidding_strategy', sa.Enum('MANUAL_CPC', 'MAXIMIZE_CLICKS', 'MAXIMIZE_CONVERSIONS', 'TARGET_CPA', 'TARGET_ROAS', name='biddingstrategy', native_enum=False), nullable=False),
    sa.Column('daily_budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ads',
    sa.Column('final_url', sa.String(length=2048), nullable=False),
    sa.Column('headlines', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('descriptions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('path1', sa.String(length=15), nullable=True),
    sa.Column('path2', sa.String(length=15), nullable=True),
    sa.Column('ad_group_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.Enum('BROAD', 'PHRASE', 'EXACT', name='matchtype', native_enum=False), nullable=False),
    sa.Column('bid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ad_group_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keywords')
    op.drop_table('ads')
    op.drop_table('ad_groups')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
